### PR TITLE
Created ListMessage Function - Filter Chat 

### PR DESCRIPTION
**Pull request by CoBatool**
Closes https://github.com/mjimenez98/chat-web-app/issues/5

- Return all posted messages that are within the date/time range
- If no range is specified, all messages are returned

1. Added `ListMessages(date-range)` Function in ChatManager
2. Updated Front-End for testing

**Chat without filter:**
pic1

**Chat with start Date no end Date:** 
pic2
**result (none)**
pic3

**Chat with start Date no end Date: (1 result)** 

**Chat with end Date no Start date:** 

**result**

**Chat with Start & End date:**

**Result:** 

**Chat when filtered with no start & end date : (All messages)** 
pic4

### CODE REVIEW

**Review by mjimenez98 — COMMENTED** [review]
Awesome! 🥳   You got it working 🙌   And you are also solving #1! Feel free to add that to your PR with `Closes #1` so it is automatically closed once this PR is merged.

Also, while I was looking through the code I thought of a few things:

### Using a different form for the filter

As opposed to posting a message in which we send the server information to be saved, here we are trying to receive information from the server based on our date parameters. Because of this, what would you think about moving the logic in the jsp and the servlet from a Post to a Get request by using a new form that is exclusive to the filter?

### Turning chatManager and filteredChat into one in the controller

Right now we are setting chatManager and filteredChat in the servlet. What if we combined the two? I only created chatManager because I wanted to test what I was posting when I created postMessage.

All requests for message retrieval should go through the ListMessages function in the model and the parameters should be (from, to, format). You have already made it so the full chat is returned if no date parameters have been received. This same logic would be 💯   if implemented in the servlet. What do you think? Do you agree?

### Java Stream API

We can tackle this in another issue, but this would greatly affect the current implementation of the ListMessages function by using the built-in filter function for Java streams.

Here is an [example](https://www.baeldung.com/java-filter-collection-by-list):
```
filteredList = originalList.stream()
      .filter(employee -> nameFilter.contains(employee.getName()))
```

### Warnings

These have been highlighted by IntelliJ:
- `Chat.jsp` line 34: Unchecked cast: 'java.lang.Object' to 'java.util.LinkedList<chat.Message>' 
- `Chat.jsp` line 65: Element br is not allowed here
- `Chat.jsp` line 67: Wrong attribute value
- `Chat.jsp` line 68: Closing tag matches nothing

### Formatting

So we stay consistent with Java conventions, I would say select all the lines in the 3 modified files and do `Command/Control + Alt/option + L` so they are automatically formatted by IntelliJ

**Comment by CoBatool** [comment]
> Awesome! 🥳 You got it working 🙌 And you are also solving #1! Feel free to add that to your PR with `Closes #1` so it is automatically closed once this PR is merged.
> 
> Also, while I was looking through the code I thought of a few things:
> 
> ### Using a different form for the filter
> As opposed to posting a message in which we send the server information to be saved, here we are trying to receive information from the server based on our date parameters. Because of this, what would you think about moving the logic in the jsp and the servlet from a Post to a Get request by using a new form that is exclusive to the filter?
> 
> ### Turning chatManager and filteredChat into one in the controller
> Right now we are setting chatManager and filteredChat in the servlet. What if we combined the two? I only created chatManager because I wanted to test what I was posting when I created postMessage.
> 
> All requests for message retrieval should go through the ListMessages function in the model and the parameters should be (from, to, format). You have already made it so the full chat is returned if no date parameters have been received. This same logic would be 💯 if implemented in the servlet. What do you think? Do you agree?
> 
> ### Java Stream API
> We can tackle this in another issue, but this would greatly affect the current implementation of the ListMessages function by using the built-in filter function for Java streams.
> 
> Here is an [example](https://www.baeldung.com/java-filter-collection-by-list):
> 
> ```
> filteredList = originalList.stream()
>       .filter(employee -> nameFilter.contains(employee.getName()))
> ```
> 
> ### Warnings
> These have been highlighted by IntelliJ:
> 
> * `Chat.jsp` line 34: Unchecked cast: 'java.lang.Object' to 'java.util.LinkedList<chat.Message>'
> * `Chat.jsp` line 65: Element br is not allowed here
> * `Chat.jsp` line 67: Wrong attribute value
> * `Chat.jsp` line 68: Closing tag matches nothing
> 
> ### Formatting
> So we stay consistent with Java conventions, I would say select all the lines in the 3 modified files and do `Command/Control + Alt/option + L` so they are automatically formatted by IntelliJ

wow great review thanks 👌 ! I 100% agree with making a GET form for the filter, I will do that !  
However, I'm not sure I understand the "Turning chatManager and filteredChat into one in the controller" , can you elaborate please?

Thanks for catching all those warnings 😅 I will fix that !

**Comment by mjimenez98** [comment]
@CoBatool [Here](https://github.com/mjimenez98/chat-web-app/pull/16/files#diff-555ace97eea29252a247fcebfa01c0b9R61-R62) we are setting both `chatManager` and `filteredChat` as attributes so we can access them in the JSP. And if we go to the JSP we can see how at the moment there are [two for loops](https://github.com/mjimenez98/chat-web-app/pull/16/files#diff-7770bcae9167f61dee8e8f932f03e500R16-R51): one for `chatManager` and one for `filteredChat`. Even for the for loop in which `filteredChat` is being probed, `chatManager` is being used for obtaining the filtered messages.

I believe the good practice here would be not to set `chatManager` as an attribute to be passed to the JSP. That way we are not giving the JSP access to the whole object. Instead, we use the `filteredMessages` attribute to access the messages in the JSP.

I could explain this better over Discord if preferred. All these variables and locations are becoming confusing to me as I write this 😅

**Review by mjimenez98 — APPROVED** [review]
✨ 

There is only one minor thing left. In `ChatServlet.java`, line 12, there is one unused import to be removed.

You are good to merge after that 👍

**Pull request merged**
